sudo: required
language: bash
services:
  - docker
before_script:
  - export APP_IMAGE=keboola-component
  - docker build . --tag=$APP_IMAGE
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x ./deploy.sh && ./deploy.sh
  on:
    tags: true
    all_branches: true
